[package]
name = "pracitice1"
version = "0.1.0"
authors = ["y-tsuzaki <y-tsuzaki@macloud.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
